### ISSUE TITLE
Refactor: create a separate model for canvases

### ISSUE THREAD

**Issue by gigamorph** [yale-web-technologies/mirador-annotations#106]
Currently retrieving annotations depend on parsing the IDs of annotation lists to determine which canvases and layers they belong to. We'd like to fix it by adding the following relations (and a new model Canvas).

```
Canvas
  has_many :annotation_lists
  has_many :annotations, through: :annotation_lists  # this may or may not be possible, please check

AnnotationLayer
  has_many: annotation_lists

AnnotationList
  belongs_to :canvas
  has_many :layers, through: :layer_lists_map
  has_many :annotations, through: list_annotations_maps
  
Annotation
  has_many :annotation_lists, through: list_annotations_maps
  has_many :canvases through :annotation_lists  # this may or may not be possible
```

Also fix AnnotationsController (and AnnotationListsController#resequence_list) so the CRUD operations on annotations will use the new relations with integrity.

After all the fix has been done, we can start using just a UUID (e.g., from `SecureRandom.uuid`) for list_id.

**Comment by mr-sigma** [comment]
Lists and layers should have a many to many relationship based off the current code base. Updating to reflect this.
