### ISSUE TITLE
Create a data backup/restore scheme

### ISSUE THREAD

**Issue by gigamorph** [yale-web-technologies/mirador-annotations#50]
Daily back-up of all contents so it can be restored immediately upon request.

**Comment by rlechich** [comment]
I created a manual backup and have scheduled daily backups.
On the current plan, heroku will one week's worth of backups.

**Comment by gigamorph** [comment]
Thank you!
Could you document the procedure at https://isa.its.yale.edu/confluence/display/CWT/Annotation+Service

**Comment by lecmaj** [comment]
Great, thanks. Here is the[ link from Heroku](https://devcenter.heroku.com/articles/heroku-postgres-backups). Let's ask the faculty next time if they prefer purchasing more or this is ok. Let's also enable for Life of the Buddha as well as 10K Rooms.
