### ISSUE TITLE
transcribing/translating across pages

### ISSUE THREAD

**Issue by mickjhunter** [yale-web-technologies/mirador-annotations#52]
Two problems here:

(1) I need to be able to connect a single transcription item to image annotations on two separate pages, because the paragraphs begin on one page and continue to the next.

(2) I can create the rectangle and transcription on the first page, but as soon as I advance to the next page the transcriptions for the previous page disappear, making it impossible to link the second rectangle to the transcription. In other words, we need the transcriptions and translations to remain in the transcription/translation panels while the images are advancing.

**Comment by ProfTina** [comment]
Mick, do you have any work around at this point?  I just hit a stretch with some notes that cross pages.

**Comment by mickjhunter** [comment]
Nope, not yet.

On Wednesday, April 20, 2016, ProfTina <notifications@github.com> wrote:

> Mick, do you have any work around at this point? I just hit a stretch with
> some notes that cross pages.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_yale-2Dweb-2Dtechnologies_mirador-2Dannotations_issues_52-23issuecomment-2D212596414&d=AwMCaQ&c=-dg2m7zWuuDZ0MUcV7Sdqw&r=COGdTjmyf1a0HAF7GM74sz3-DPR1xHcGhXZE3jVGTT0&m=3qWB91LUAMYSQxXzIyfR50_i6HUhCH8APVGltptqirE&s=_dclYq4EN1PeCX2e4slfzFgqB5KthDAUEIM3_pADols&e=>
>


-- 
Michael Hunter (mick.hunter@yale.edu)
Department of East Asian Languages and Literatures
Yale University
P.O. Box 208236
New Haven, CT 06520-8236
(203) 432-7529 (office)

**Comment by gigamorph** [comment]
It is not yet supported by IIIF nor Mirador at the fundamental level. We will have to come up with something though.

**Comment by gigamorph** [comment]
Re-created the issue at
https://github.com/yale-web-technologies/mirador-project/issues/7

Closing this one.
