### ISSUE TITLE
controlling the order of the annotation list

### ISSUE THREAD

**Issue by mickjhunter** [yale-web-technologies/mirador-annotations#53]
Is there any way to rearrange the order of transcription/translation items? I just created two transcription items, but they're currently being displayed in the opposite order from the text itself. Any way to change it?

Thanks!

**Comment by Quintman** [comment]
I think this will be an issue for LOTB as well. Annotations added out of sequence will create text-flow problems.

**Comment by gigamorph** [comment]
Created a parent issue at 
https://github.com/yale-web-technologies/mirador-project/issues/8

As per this ticket Roy will develop the backend code for this functionality.

**Comment by rlechich** [comment]
The backend code now contains this functionality and is currently deployed on the staging servers.
Needs to be tested against the Mirador app once the functionality is closed, then we can deploy to production and close this issue.

**Comment by rlechich** [comment]
This works against the Mirador app so I am closing this issue.
