### ISSUE TITLE
speed?

### ISSUE THREAD

**Issue by ProfTina** [yale-web-technologies/mirador-annotations#60]
Hi guys,
We are just wondering whether the slowness is related to the fact that you are working on it right now or whether it is just slow?
Thanks,
Tina

**Comment by rlechich** [comment]
Hi Tina,

Are you seeing slowness more in image loading or annotation loading?

- Roy

**Comment by ProfTina** [comment]
Image loading.

**Comment by gigamorph** [comment]
I'm afraid initial image loading is just slow. I think it has more to do with the image server. If it is a big problem we can discuss it in the next meeting.

**Comment by gigamorph** [comment]
Closing this, assuming the question answered for now.
Will create another issue if it continues to be a problem.
