### ISSUE TITLE
slant

### ISSUE THREAD

**Issue by ProfTina** [yale-web-technologies/mirador-annotations#61]
Dear Guys,
Pages like this are going to be uploaded all the time.  (This one is because the original was photocopied as part of the photoreprint at an angle.  It is impossible to fix from the scanning perspective.)  Is there any way that we can build in some way to retilt them to perpendicular?
Thanks!
Tina

<img width="2560" alt="screenshot 2016-04-15 10 57 45" src="https://cloud.githubusercontent.com/assets/18328875/14565421/02d67d66-02f9-11e6-92a4-7f04b0e8ea55.png">

**Comment by gigamorph** [comment]
It has to be either re-scanned or modified. We can probably decide on who will do it in a meeting.
