### ISSUE TITLE
mouse pass?

### ISSUE THREAD

**Issue by ProfTina** [yale-web-technologies/mirador-annotations#62]
How do I get to look at the annotations by passing my mouse over the image?  I have entered annotations on this page and can figure out how to look at what I have entered but can't figure out how to correlate them to the image.
Thanks!
Tina

<img width="2560" alt="screenshot 2016-04-15 11 38 11" src="https://cloud.githubusercontent.com/assets/18328875/14566690/952d4b54-02fe-11e6-8cf7-bb0fcdc1cbf3.png">

**Comment by gigamorph** [comment]
Answered in person.
