### ISSUE TITLE
polygon

### ISSUE THREAD

**Issue by ProfTina** [yale-web-technologies/mirador-annotations#63]
I can make a polygon around the image, but I cannot get my mouse to release it and allow me to annotate the polygon.  Can you help me figure out how to do that or is there currently a bug?

**Comment by gigamorph** [comment]
When you close the polygon, in other words, when you come back to the first point that you clicked to create the polygon, you have to double-click instead of single-click. - I know this is not intuitive at all.

**Comment by ProfTina** [comment]
Thanks!
