### ISSUE TITLE
Mirador Crashing

### ISSUE THREAD

**Issue by Quintman** [yale-web-technologies/mirador-annotations#65]
Mirador occasionally seems to crash, screen turns blank gray, requiring a refresh of the page in the browser. It seems to happen soon after saving a new annotation, but not every time. (Mac OS 10.11.4 on Chrome)

**Comment by gigamorph** [comment]
Re-created the issue at 
https://github.com/yale-web-technologies/mirador-project/issues/11

Closing this one.
