### ISSUE TITLE
Need to add new annotation layers

### ISSUE THREAD

**Issue by Quintman** [yale-web-technologies/mirador-annotations#66]
For LOTB annotations, we need additional layers: Inscription-Tibetan, Inscription-English, Manual-Tibetan, Manual-English, Sources, etc. For ex: I can't save an English inscription that I have linked to the Tibetan because I can't choose a layer for it. (An error box appears saying "choose layer").

**Comment by rlechich** [comment]
Andrew I have added these to our staging area and we can review them tomorrow at our meeting. And we can add any that I haven't added at that point.

**Comment by rlechich** [comment]
OK, these have all been added to the staging and prod environments
