### ISSUE TITLE
Can't tell if freehand annotations are "closed"

### ISSUE THREAD

**Issue by Quintman** [yale-web-technologies/mirador-annotations#67]
I think Seong mentioned that annotations drawn freehand need to be "closed", which is allows the annotation data to appear on mouseover. But it is difficult to tell when a freehand annotation is closed. Any suggestions? Thanks!

**Comment by gigamorph** [comment]
Re-created the issue at 
https://github.com/yale-web-technologies/mirador-project/issues/6

Closing this one.
