### ISSUE TITLE
Not sure if linked annotations are really linked

### ISSUE THREAD

**Issue by Quintman** [yale-web-technologies/mirador-annotations#68]
It's not clear if the links between annotations are really there. For example: I draw an annotation and add the text  "Chapter 24, Scene 1." Then I create a new annotation from the annotation window, select "Sun of Faith Tibetan" layer, add text, and create link to the original annotation drawing. Make another annotation for Sun of Faith English and link it to the original annotation drawing. Now, when I select the original annotation from the annotation window, the drawing lights up. But if I click on the Tibetan or English, nothing happens. Hard to tell if they are actually linked.

**Comment by gigamorph** [comment]
Re-created the issue at
https://github.com/yale-web-technologies/mirador-project/issues/5

Closing this one.
