### ISSUE TITLE
trouble drawing polygons on eyebrow or bottom transcriptions

### ISSUE THREAD

**Issue by rlechich** [yale-web-technologies/mirador-annotations#75]
trouble drawing polygons on eyebrow or bottom transcriptions because no available margin space on which to draw.
Is it possible to increase zoom-ability or somehow increase the margin sizes?

**Comment by gigamorph** [comment]
Recreated the issue at
https://github.com/yale-web-technologies/mirador-project/issues/2

Closing this one.
