### ISSUE TITLE
Enforce unique IDs

### ISSUE THREAD

**Issue by gigamorph** [yale-web-technologies/mirador-annotations#81]
Please enforce unique IDs on all objects. Any attempt to create a new object with an existing ID should cause an error and handled appropriately.

**Comment by rlechich** [comment]
The mapping models:  annotations, annotation_lists and annotation_layers use GUID generation to build unique IDs
The two mapping models:  layer_lists_maps and list_annotations_maps enforce unique id's in code.
This is related to an earlier issue where the retrieve were possibly returning the same record more than once.
I am closing this issue for now; we can re-open if necessary.
