### ISSUE TITLE
Layer ID gets corrupt when saving a new annotation

### ISSUE THREAD

**Issue by gigamorph** [yale-web-technologies/mirador-annotations#87]
For example, when I set the layer ID to `"http://mirador-annotations-lotb-stg.herokuapp.com/layers/Chapters"` in the request, the server says the creation is successful. But a search with `getAnnotationsViaList` returns the annotation with layer ID set to `"http://mirador-annotations-lotb-stg.herokuapp.com/layers/Chapters_http://manifests.ydc2.yale.edu/LOTB/canvas/panel"`.

**Comment by rlechich** [comment]
Fixed.  The data was ok, but the new annotation retrieval method using lists was not always parsing the layer_id from the list_id correctly.
